#!/bin/bash

print_usage()
{
    echo "Usage: $0 INSTALL_DIR"
    exit 1
}

trap_exit()
{
    echo "[Err] deploy failed"
}

[ -z $1 ] && print_usage

[ `id -u` -ne 0 ] && echo "are you root?" && exit 1

INSTALL_DIR=$1
[ ! -d "$INSTALL_DIR" ] && echo "[Err] install dir not exist - $INSTALL_DIR" && exit 1
INSTALL_DIR=$(cd $INSTALL_DIR; pwd)
DEST_DIR=$INSTALL_DIR/server
[ ! -x "$DEST_DIR/bin/mediawise" ] && echo "[Err] cgi module not installed" && exit 1
CONF_FILE="media_wise_cgi.conf"

echo "## Generated by installation script of Mediawise Server##" > $CONF_FILE
echo "Alias /service/mediawise $DEST_DIR/bin/mediawise" >> $CONF_FILE
echo "DefaultInitEnv MEDIAWISE_HOME \"$DEST_DIR\"" >> $CONF_FILE
#echo "SetEnv MEDIAWISE_HOME \"$DEST_DIR\"" >> $CONF_FILE
#echo "MaxRequestLen 10240000" >> $CONF_FILE

echo "<Location /service/mediawise>" >> $CONF_FILE
echo -e "\tSetHandler fcgid-script" >> $CONF_FILE
echo -e "\tOrder Allow,Deny" >> $CONF_FILE
echo -e "\tAllow from all\n" >> $CONF_FILE
echo -e "\tOptions +ExecCGI -MultiViews +SymLinksIfOwnerMatch" >> $CONF_FILE
echo "</Location>" >> $CONF_FILE
mv $CONF_FILE "/etc/apache2/conf.d/"

/etc/init.d/apache2 restart

trap EXIT
echo " * Success"
